version: '3.1'

services:

  db-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'db-dev'
    ports:
      - 5432:5432
  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'db-test'
    ports:
      - 8080:5432